---
title: "Sharing Maps with R Markdown and Leaflet"
author: "Pablo Rosales"
date: "12/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
library(leaflet)
```


# Guatemala: 
## Top 3 Places to Visit
```{r echo = FALSE}
 content_tikal <- paste(
   sep="<br/>",
   "<b>1 <a href='https://whc.unesco.org/en/list/64'> Tikal </a> </b>",
   "<font color=green>Heart of the Maya Civilization</font>"
   )

 content_atitlan <- paste(
   sep="<br/>",
   "<b>2 <a href='https://wikitravel.org/en/Lake_Atitl%C3%A1n'>  Lake Atitlan </a> </b>",
   "<font color=blue>The most beautiful lake in the World, surrounded by 3 volcanoes</font>"
 )

 content_antigua <- paste(
   sep="<br/>",
   "<b>3  <a href='https://whc.unesco.org/en/list/65'> Antigua </a> </b>",
   "<font color=red> The City of the Roses</font>"
 )

 my_map <- leaflet() %>% addTiles() %>% addPopups(lat=17.221944 , lng=-89.622778, content_tikal, options=popupOptions(closeButton=FALSE)) %>% addPopups(lat=14.6999972, lng=-91.1999992, content_atitlan) %>% addPopups(lat=14.5666644, lng=-90.7333304, content_antigua)


my_map
``` 

#### Analysis date:  December 5, 2018.
